# Generated by Django 5.1.1 on 2024-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_question_quiz_answer_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Answer 1'), (2, 'Answer 2'), (3, 'Answer 3'), (4, 'Answer 4')], default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
