# Generated by Django 4.2 on 2024-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_instrument_termin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('pdf', models.FileField(upload_to='courses/pdf')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
            ],
        ),
    ]
